[package]
name = "data_structs"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-segmentation = "1.12.0"
serde_json = "1.0"
bincode = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
# Add other shared dependencies as needed
